import { GroupBox, ListView, Button } from "std-widgets.slint";
import { Backend, FocusCandidate } from "../backend.slint";

component Tile inherits Rectangle {
    in property <string> engine;
    private property <bool> active;
    height: text.height + 8px;

    states [
        active when active: {
            state-area.opacity: 0.07;
            selection-area.opacity: 0.1;
        }
        hover when touch-area.has-hover: {
            state-area.opacity: 0.07;
        }
    ]

    selection-area := Rectangle {
        x: 0;
        opacity: 0;
        background: #FFFFFF;
        width: 10px;
    }

    state-area := Rectangle {
        opacity: 0;
        background: #FFFFFF;
        Rectangle {
            opacity: 0;
            width: parent.width - 5px;
            height: parent.height - 5px;
        }

        animate opacity { duration: 75ms; }
    }

    text := Text {
        text: engine;
    }

    touch-area := TouchArea {
        clicked => {
            active = !active;
        }
    }
}

component Profiles inherits GroupBox {
    title: "Profiles";
    ListView {
        for engine in Backend.stored-engines: Tile {
            engine: engine;
        }
    }
}

component Toolbar inherits GroupBox {
    forward-focus: add;
    HorizontalLayout {
        alignment: end;
        property <FocusCandidate> focus-candidate: Backend.focus-candidate;
        function focus-helper() {
            if (focus-candidate == FocusCandidate.add-button) {
                add.focus();
            }
        }
        changed focus-candidate => {
            focus-helper();
        }
        add := Button {
            text: "󰐙";
            clicked => {
                Backend.clear-signal = !Backend.clear-signal;
                Backend.rpanel-interactable = true;
                Backend.set_focus_candidate(FocusCandidate.add-button);
            }
        }

        delete := Button {
            text: "";
            init => {
                Backend.update-focus-candidate(1);
            }
        }
    }
}

export component LeftPanel inherits VerticalLayout {
    forward-focus: toolbar;

    Profiles { }

    toolbar := Toolbar { }
}
