import { GroupBox, TabWidget, ListView, TextEdit, Button, ComboBox, LineEdit, AboutSlint } from "std-widgets.slint";
import { Backend } from "../backend.slint";

component ConversionEngine inherits GroupBox {
    property <[string]> engines: Backend.engines;
    title: "Conversion engine";
    ComboBox {
        model: engines;
    }
}

component IOKind inherits GroupBox {
    property <bool> clear-signal: Backend.clear-signal;
    changed clear_signal => {
        path.text = "";
        extension.text = "";
    }
    in property <string> kind;
    title: kind;
    VerticalLayout {
        HorizontalLayout {
            path := LineEdit {
                placeholder-text: "Relative path";
            }

            Button {
                text: "";
            }
        }

        extension := LineEdit {
            placeholder-text: "File extension";
        }
    }
}

component ConversionEngineSettings inherits GroupBox {
    title: "Conversion engine settings";
    TabWidget {
        Tab {
            title: "Options";
            HorizontalLayout {
                TextEdit { } // TODO: change for a more adhoc widget
            }
        }

        Tab {
            title: "Ignore patterns";
            HorizontalLayout {
                TextEdit { }
            }
        }
    }
}

component Toolbar inherits GroupBox {
    HorizontalLayout {
        alignment: end;
        popup := PopupWindow {
            AboutSlint {}
        }
        Button {
            horizontal-stretch: 0;
            text: "";
            clicked => {
                popup.show();
            }
        }

        Rectangle {
            width: 10px;
        }

        Button {
            horizontal-stretch: 0;
            text: "";
            clicked => {
                Backend.save_profile();
            }
        }

        Button {
            horizontal-stretch: 0;
            text: "";
        }
    }
}

export component RightPanel inherits VerticalLayout {
    ConversionEngine { }

    IOKind {
        kind: "Source";
    }

    IOKind {
        kind: "Output";
    }

    ConversionEngineSettings { }

    Toolbar { }
}
