export component Tile inherits Rectangle {
    in property <string> engine;
    private property <bool> active;
    height: text.height + 8px;

    states [
        active when active: {
            state-area.opacity: 0.07;
            selection-area.opacity: 0.1;
        }
        hover when touch-area.has-hover: {
            state-area.opacity: 0.07;
        }
    ]

    selection-area := Rectangle {
        x: 0;
        opacity: 0;
        background: #FFFFFF;
        width: 10px;
    }

    state-area := Rectangle {
        opacity: 0;
        background: #FFFFFF;
        Rectangle {
            opacity: 0;
            width: parent.width - 5px;
            height: parent.height - 5px;
        }

        animate opacity { duration: 75ms; }
    }

    text := Text {
        text: engine;
    }

    touch-area := TouchArea {
        clicked => {
            active = !active;
        }
    }
}
